# Generated by Django 5.2.3 on 2025-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('oyo', 'Oyo'), ('lagos', 'Lagos'), ('kaduna', 'Kaduna')], max_length=100),
        ),
    ]
