# Generated by Django 5.2.3 on 2025-06-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_size_alter_cartitem_unique_together_productsize_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
